### ISSUE TITLE
sqltex with xml

### ISSUE THREAD

**Issue by GTres** [oveas/sqltex#1]
Hello,

Please excusem for my bad English,

You are doing an excelent work, I want to use sqltex but my data are in an xml  file. Do you have any latex example that use an xml datasource?

**Comment by oveas** [comment]
Hi,
You English is fine ;)
I'm sorry to say XML datasources are not supported in SQLTeX; it should be possible to use this if there's some SQL for XMLfiles tool, but I am not aware of the existence of such tool.

Hope this helps,
Oscar

**Comment by GTres** [comment]
Thanks Oscar, I'll be looking for and I will tell

2016-03-20 9:55 GMT-05:00 Oscar van Eijk notifications@github.com:

**Comment by GTres** [comment]
Hi Oscar,

I'm trying with postgreSQL 9.5.1 database and Windows 8.1
I have not installed Perl.

this is my test.tex:

`\documentclass[article]
\pagestyle{empty}\sqldb[postgres,postgres]{probarlatex}
\begin{document}
Hello database
\end{document}`

In my SQLTeX.cfg i changed the line
`dbdriver =  mysql`
to
`dbdriver       = PostgreSQL`

In de command line I wrote:
`SQLTeX.v2.0 -c SQLTeX.cfg -r SQLTeX_r.dat -s http:\\localhost:5432 test.tex`

end i get an error:
`
C:\Users\mydir\Documents\pruebas de latex\sqltex>SQLTeX.v2.0 -c SQLTeX.cfg -
r SQLTeX_r.dat -s http:\\localhost:5432 test.tex
Processing file test.tex...
Connect to database probarlatex on http:\\localhost:5432 as user postgres using
a password
install_driver(Pg) failed: Can't load 'C:\Users\mydir\AppData\Local\Temp\par-6775123c6c65726d6f\cache-fff74b9b123ed2ac6a6211d233cd0199f83ee567\3ed7194c.xs.dll' for module DBD::Pg: load_file:No se puede encontrar el modulo especificado at C:/Strawberry/perl/lib/DynaLoader.pm line 193, <$fileIn> line 2.
  at C:/Strawberry/perl/site/lib/PAR/Heavy.pm line 120.
Compilation failed in require at (eval 15) line 3, <$fileIn> line 2.
Perhaps a required shared library or dll isn't installed where expected
 at script/SQLTeX.pl line 370.`

Do you know what happens?

**Comment by oveas** [comment]
Hi,
First of all,  sorry for my late reply; I've been away for a while.

I'm not a Windows user myself, so I can't reproduce it, but I suppose the executable is missing the drivers. I will look into that and build a new executable asap. Since I cannot test it, I might ask you to test before I actually release the update.

Regards,
Oscar

**Comment by GTres** [comment]
Hi Oscar,

I solve the problem:
1. Install perl
2. Instal DBI package in perl
3. uninstall lyx, my pc search into lyx directories for DBI package perl.
4. setup system variables, mybe step 3 was not necesary.

After that all fine.

2016-04-12 3:54 GMT-05:00 Oscar van Eijk notifications@github.com:
