### ISSUE TITLE
Nonstandard behaviour for path management

### ISSUE THREAD

**Issue by mwamp** [oveas/sqltex#2]
Thanks for this useful and simple tool.
I have one issue and one bug here 
ISSUE : There is something non standard going on with the output file (-o option). You grab the full path of the input file and insist that the output path will start from there. I think this is non standard.
Clarification : SQLTeX -o path_out/out.tex  path_in/input.stx goes to path_in/path_out/output.tex

BUG : Dots are not taken into account in regex matching of input path : 
SQLTeX ../input
tries to find an input file at ../../input

**Comment by oveas** [comment]
Thanks for you feedback. I would consider both as bugs; what you describe as an issues was not intended.
Both will be fixed in the next release.

**Comment by oveas** [comment]
Both bugs have been fixed and will be available in the upcoming 2.1 release.
