### ISSUE TITLE
SQLTEX in windows installation

### ISSUE THREAD

**Issue by Silpa1108** [oveas/sqltex#5]
@oveas 
Hello  ,
I was trying to install sqltex in windows os to work with mysql database.
The sqltex.pl is not working and its showing configeration file is missing error.I have kept all contents of  src folder in a single directory and have installed all the prerequisites mentioned in the documentation.Also tried running the .exe file but not working as well.
Could you please help me as I dont know what went wrong .

**Comment by Silpa1108** [comment]
[
![image](https://user-images.githubusercontent.com/102862789/161386838-764610cb-3984-404f-872b-c63283ea2c49.png)
](url)

**Comment by Silpa1108** [comment]
Running the .exe file gives missing inputfile error.

**Comment by oveas** [comment]
Hi @Snowinghard,

On Windows, you don't need the src folder, you only need 3 files: the .exe file, the replacements file (_SQLTeX_r.dat_) and the config file (_SQLTeX.cfg_), all in the same directory.
No installation is required. The message you receive means SQLTeX works fine, but you didn't specify an input file.

You can type _sqltex.exe --help_ for more info, or look at section 4 in the [documentation](https://github.com/oveas/sqltex/releases/download/v2.1/SQLTeX.pdf) how you can continue from here.
