### ISSUE TITLE
Using SQL Server Management studio(SSMS) data base

### ISSUE THREAD

**Issue by Silpa1108** [oveas/sqltex#6]
@oveas How can I use MSSQL database with this package.What changes should I make?Can I use ODBC driver for this.

**Comment by Silpa1108** [comment]
I am using MSSQL data base.Please help

**Comment by oveas** [comment]
Hi @Snowinghard, MSSQL is currently not supported. I don think it will be very hard to add, but I cannot test it myself.
If I can create a test version is the upcoming days, will you be able to test this then?

**Comment by Silpa1108** [comment]
Hi @oveas ,Thank you for the reply.
I will be able to test if you provide with the test version.I have  both MSSQL and ODBC drivers installed in my system.

**Comment by oveas** [comment]
Maybe there's a shortcut already: if your database server runs on the same system where you wanna use SQLTeX, please change the db driver in your configuration file SQLTeX.cfg:

`dbdriver = ODBC:Driver={SQL Server};Database=`

You need to change 1 line in the perl script: on line 12097, change:
`		my ($ck, $cv) = split /=/, $main::line;`
in
`		my ($ck, $cv) = split /=/, $main::line, 2;`
(add  ', 2' at the end)

Then, in your \sqldb statement, don't specify 'host'. Please let me know if that works.

**Comment by Silpa1108** [comment]
I tried, its not working.I think its not taking ODBC SQL Server driver


![image](https://user-images.githubusercontent.com/102862789/162426609-b9fe7c8a-7cfe-46b5-85a6-1dca9dde5825.png)
Error states :Connect to database AdventureWorksDW2012 on localhost as user Silpa using a password
DBI connect('Driver:database=AdventureWorksDW2012','Silpa',...) failed: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (SQL-IM002) at script/SQLTeX.pl line 518.

**Comment by oveas** [comment]
Just edited my comment again, missed something, but never mind: this quick hack is not going to work.
I'll send you a test version asap.

**Comment by Silpa1108** [comment]
thanks a lot.I was stuck on this.....

**Comment by oveas** [comment]
Hi @Snowinghard, I created a testversion: see attached.
The zip-file contains SQLTeX.exe; you can just copy that file over your existing copy. Next, in your SQLTeX.cfg, set your dbdriver to ODBC:
`	dbdriver		= ODBC`

I prepared 3 testscenario's (couldn't test anything myself): if `ODBC` doesn't work, please try `MSSQL` or `MSSQL2`.
Please let me know which of these work or, if none of them does, which errors you get for each.

[SQLTeX.zip](https://github.com/oveas/sqltex/files/8511779/SQLTeX.zip)

**Comment by Silpa1108** [comment]
@oveas  I tried all three dbdrivers and connection failed is shown as error.

_(image removed since the screenshot contained possible sensitive data)_

**Comment by Silpa1108** [comment]
Server keyword not supplied was the error.Should we provide server name as localhost or something.

**Comment by oveas** [comment]
Please give that a try: in your tex input file make the hostname explicit:
`\sqldb{user=...,passwd=?,host=localhost}`
If that works, I just need to change the way the default is handled (please let me know which of the options all work).
If not, I need to dig further.

**Comment by Silpa1108** [comment]
@oveas  Hi,
Now after including the localhost its working fine and the database is connected and its pulling the data.The dbdriver is set as ODBC.
Thanks a lot.

**Comment by Silpa1108** [comment]
Actually its working with MSSQL and MSSQL2 'dbdriver' as well.

**Comment by oveas** [comment]
Ok, thanks for your help with testing.

I don know when I'll release a new version, but until then you can work with this version. Please stick to the use of 'ODBC'; when an official version will be released, that will be the one supported.
For now you need to specify 'localhost' in all your texfiles as you did for this test. In the official version that won be necessary anymore (but it won't hurt so you can keep it in there if you like).

This issue will remain open as a reference to others; I'll close it when 2.2 is final.

**Comment by oveas** [comment]
Closing the issue; this is now  part of SQLTeX v2.2
