### ISSUE TITLE
How to use sqlsetparams with CLI parameters?

### ISSUE THREAD

**Issue by kpckpc** [oveas/sqltex#8]
First of all, thanks for this great package.
I am currently struggling with getting an input parameter in sqlsetparams.
With a fixed select statement it works fine, but I want to make it dependant on a CLI parameter.
Without sqlsetparams but with using the CLI parameter works fine as well.
It is the combination that is failing for me
$PAR1 seems to be overwritten by the loopfunction of sqlsetparams itself.
${PAR1} replaces correctly, but everything after the parameter gets lost, so also my closing quote. (I am passing a string)

As a workaround the following works by moving to PAR2, but somehow need another dummy variable.
SQLTeX --multidoc-numbered test.tex dummy "string" dummy

**Comment by kpckpc** [comment]
Oops, my workaround only worked for the first item. All other the workaround fails.
I am lacking proper perl skills. As a quick fix, I modified line 906 to keep passing the other input parameters, just modifying the first:
```
   if (($main::multidoc_cnt > 0) && $main::multidoc) {
                        $statement =~ s/\$PAR1/$multidoc_par/g;
                        for (my $i = 2; $i <= $#ARGV; $i++) {
                                $statement =~ s/\$PAR$i/$ARGV[$i]/g;
                        }
                } else {
                        for (my $i = 1; $i <= $#ARGV; $i++) {
                                $statement =~ s/\$PAR$i/$ARGV[$i]/g;
                        }
                }

```

**Comment by oveas** [comment]
I'm not sure I understand what you're trying to achieve. You want to create multiple files, but in stead of a database value (retrieved with setparams) you want an argument given at cli to be the trigger for each output file.
But that argument will be the same for all, so what will be the difference? Or will that be a list of arguments?

Multidoc mode just simulates multiple calls to SQLTeX with only 1 cli argument per call.
Can you give an example of what you'ro looking for?

**Comment by kpckpc** [comment]
I have a table with references to an items table, base on a project name. This I gave to the sqlsetparams
SELECT item_id FROM samples WHERE project='$PAR1'

Then I use this id, to select from an items table, however the database does not give unique results only in 'item_id'(=PAR1), the query would also have to know about the original PROJECT. Do not ask me why, this is how the company set it up.
So the query would need to know the both the item_id(=PAR1) as the project input parameter as well.
SELECT item FROM items WHERE id=$PAR1 AND project='$PROJECT'

**Comment by oveas** [comment]
Ah ok, I got what you mean. That is not supported but it would be a useful feature. Give me a few days to look into it, because I don´t think there's a workarounf possible but implementing it shouldn't be that hard.

**Comment by oveas** [comment]
I just pushed a new commit that should make possible what you try to achieve. It's not documented yet, but a short description of how it should work:
* You can use parameters now in \sqlsetparams{}. Multiple parameters are now supported.
* The result of \sqlsetparams{} (which still must be 1 field per row) will be used as next $PAR in all documents that are generated (1 document per row), so if you used 1 parameter in \sqlsetparams{}, the result will be used for $PAR2, if you used 2, the result will be used for $PAR3 etc.
* Is you need more parameters in the rest of your document, you can add them, but make sure to use a dummy parameter on the location where the \sqlsetparams{} will be used. In your example that would be:
\sqlsetparams{SELECT item_id FROM samples WHERE project='$PAR1'}

further down, e.g.:
\sqlfield{SELECT something FROM items WHERE item_id=$PAR2 AND something_else='$PAR3'}

In this case, you need too pass the parameters: ITEMID dummy SOMETHINGELSE

Note this implementation might change in the next official release; this is just a test version!

Please let me know if this works for you.

**Comment by oveas** [comment]
I pushed a new commit today with the implementation as it will be in v2.2 when that'll be released.
Forget those dummy parameters, you can just use $PAR1..$PARn for commandline parameters in all your statements, including sqlsetparams.

The output of sqlsetparams will not be used to replace $MPAR1..$MPARn (yes, from now on sqlsetparams can return multiple fields per row).

Documentation is not updated yet and this is not yet released but you can download from the latest commit.

**Comment by oveas** [comment]
Documentation is now also updated, you can fetch the latest TeX file [here](https://github.com/oveas/sqltex/blob/master/doc/SQLTeX.tex)

**Comment by oveas** [comment]
Closing the issue; this is now  part of SQLTeX v2.2
